version: '3'
services:
  mysql_master:
    image: mysql:5.7
    env_file:
      - ./master/mysql_master.env
    container_name: "mysql_master"
    restart: "no"
    ports:
      - 4406:3306
    volumes:
      - ./master/data:/var/lib/mysql
    command: --skip-host-cache --skip-name-resolve --server-id=1 --log-bin='mysql-bin-1.log' --binlog_format='ROW' --binlog_do_db='mydb' --gtid_mode='ON' --enforce_gtid_consistency='ON'
    networks:
      - overlay

  mysql_slave:
    image: mysql:5.7
    env_file:
      - ./slave/mysql_slave.env
    container_name: "mysql_slave"
    restart: "no"
    ports:
      - 5506:3306
    depends_on:
      - mysql_master
    volumes:
      - ./slave/data:/var/lib/mysql
    command: --skip-host-cache --skip-name-resolve --server-id=2 --log-bin='mysql-bin-1.log' --relay-log='mysql-relay-bin.log' --binlog_do_db='mydb' --gtid_mode='ON' --enforce_gtid_consistency='ON'
    networks:
      - overlay

  mysql_slave2:
    image: mysql:5.7
    env_file:
      - ./slave2/mysql_slave2.env
    container_name: "mysql_slave2"
    restart: "no"
    ports:
      - 6606:3306
    depends_on:
      - mysql_master
    volumes:
      - ./slave2/data:/var/lib/mysql
    command: --skip-host-cache --skip-name-resolve --server-id=3 --log-bin='mysql-bin-1.log' --relay-log='mysql-relay-bin.log' --binlog_do_db='mydb' --gtid_mode='ON' --enforce_gtid_consistency='ON'
    networks:
      - overlay

networks:
  overlay:

