server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql:replication://localhost:4406,localhost:5506/mydb?allowSourceDownConnections=true&allowReplicasDownConnections=true
    username: root
    password: 111
    #    url: jdbc:mysql://localhost:4406/mydb
    #    url: jdbc:mysql://localhost:5506/mydb
  #    url: jdbc:mysql:loadbalance://localhost:4406,localhost:5506/mydb?loadBalanceConnectionGroup=first&allowMasterDownConnections=false

  liquibase:
    change-log: db/changelog/changelog.xml