server:
  port: 80

spring:
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL}

  liquibase:
    change-log: db/changelog/changelog.xml

  rabbitmq:
    host: ${CLOUDAMQP_HOST}
    username: ${CLOUDAMQP_USER}
    password: ${CLOUDAMQP_PASSWORD}
    virtual-host: ${CLOUDAMQP_VHOST}

  redis:
    url: ${STACKHERO_REDIS_URL_CLEAR}