server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/new_schema
    username: root
    password: developer

  liquibase:
    change-log: db/changelog/changelog.xml

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit
    password: rabbit

  redis:
    url: redis://:@localhost:6379