server:
  port: 80

spring:
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL}

  liquibase:
    change-log: db/changelog/changelog.xml

  rabbitmq:
    addresses: ${CLOUDAMQP_URL}

  redis:
    url: ${STACKHERO_REDIS_URL_CLEAR}