server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/new_schema
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  liquibase:
    change-log: db/changelog/changelog.xml